config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'groups#index', as: :authenticated_root
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    unauthenticated do
      root 'home#index'
    end
  end

  resources :groups do
    resources :operations
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :author_id
  has_many :operations, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :icon, presence: true

  def recent_transactions
    operations.order(created_at: :desc).limit(5)
  end
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :groups

  validates :name, :amount, :author_id, presence: true
  validates :amount, numericality: { greater_than: 0, only_integer: true, less_than: 100_000_000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :operations, foreign_key: 'author_id', dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  # before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to root_url, alert: exception.message
  # end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password) }
  end

  private

  def after_sign_in_path_for(_resource)
    groups_path # Redirect to groups index after sign-in
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show update destroy]

  def index
    @user = current_user
    @groups = Group.all.where(author_id: current_user.id)
  end

  def create
    add_group = Group.new(group_params)
    add_group.author_id = current_user.id

    if add_group.save
      redirect_to groups_path, notice: 'Category was successfully created'
    else
      render :new, alert: 'Failed to create category'
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path, notice: 'Category was successfully updated'
    else
      render :edit, alert: 'Failed to update category'
    end
  end

  # GET /categories/1 or /categories/1.json
  def show
    @group = Group.find(params[:id])
    @operations = Operation.where(group_id: @group.id).order(id: :desc)
    @total_amount = @operations.sum(:amount)
  end

  def destroy
    @group = Group.find(params[:id])

    if @group.destroy
      redirect_to groups_path, notice: 'Category was successfully removed'
    else
      render :index, alert: 'Failed to remove category'
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def determine_layout
    user_signed_in? ? 'application' : 'unauthenticated'
  end

  def group_params
    params.permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[show update destroy]

  def index
    @group = Group.find(params[:group_id])
    @operations = Operation.where(group_id: @group.id).order(id: :desc)
    @total_amount = @operations.sum(:amount)
  end

  def new
    @group = Group.find(params[:group_id])
    @operation = Operation.new
  end

  def create
    @group = Group.find(params[:group_id])
    @operation = Operation.new(operation_params)
    @operation.group_id = @group.id
    @operation.author_id = current_user.id

    if @operation.save
      redirect_to group_path(@group), notice: 'Transaction was successfully created.'
    else
      render :new, alert: 'Failed to add transaction'
    end
  end

  def destroy
    @operation = Operation.find(params[:id])

    if @operation.destroy
      redirect_to group_operations_path, notice: 'Transaction was successfully destroyed.'
    else
      render :index, alert: 'Failed to remove transaction'
    end
  end

  private

  def set_operation
    @item = Operation.find(params[:id])
  end

  def operation_params
    params.require(:operation).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<main class="splash_screen">
<div class="app_name">  
<nav>
  <%= link_to image_tag("https://img.icons8.com/sf-regular/48/ffffff/exit.png"), destroy_user_session_path, :method => :delete %>
  <h1 class="categories">CATEGORIES</h1>
  <img src="https://img.icons8.com/sf-black/48/ffffff/search.png"/>
</nav>
<main>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="card-list">
    <% @groups.each do |category| %>
        <div class="card hover">
          <div class="flex-row">
              <div class="cat-image">
                <%= image_tag category.icon rescue image_tag('https://img.icons8.com/officel/48/000000/box.png', alt: "Category Icon") %>
              </div>
              <div>
                <h2><%= link_to category.name, group_path(id: category.id) %></h2>
                <br/>
                <hr />
                <br/>
                <p><%= l category.created_at.to_date, format: :long %></p>
              </div>
            </div>
            <div class="cat-total">
              <p>$<%= Operation.where(group_id: category.id).sum (:amount) %></p>
              <br/>
              <%= button_to 'Delete', group_path(id: category.id), method: :delete, class: 'del-btn' %>
            </div>
        </div>
    <% end %>
  </div>
  <button class="green-btn" type="button" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Add a new category">
    <%= link_to 'Add a new category', new_group_path %>
  </button>
</main>
</main>

app/views/groups/new.html.erb
<nav>
  <div>
    <%= link_to image_tag("https://img.icons8.com/ios-filled/48/ffffff/long-arrow-left.png"), groups_path, class: "btn" %>
  </div>
  <h1>NEW CATEGORY</h1>
  <img src="https://img.icons8.com/sf-black/48/ffffff/search.png"/>
</nav>
<div class="center">
  <h1 class="color-white">ADD A NEW CATEGORY</h1>
  <div class="card-list">
    <%= form_with model: @group, url: groups_path do |f| %>
    <br>
    <%= f.text_field :icon, placeholder: "Enter the icon link", class: "form-field" %>
    <br/>
    <br/>
    <%= f.text_field :name, placeholder: "Name", class: "form-field" %>
    <br/>
    <br/>
    <%= f.submit "Save", class: "green-btn" %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<nav>
  <div>
    <%= link_to image_tag("https://img.icons8.com/ios-filled/48/ffffff/long-arrow-left.png"), groups_path, class: "btn"  %>
  </div>
  <h1 class="color-white">TRANSACTIONS</h1>
  <img src="https://img.icons8.com/sf-black/48/ffffff/search.png"/>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="banner">
<div class="cat-image">
    <%= image_tag @group.icon rescue image_tag 'https://img.icons8.com/officel/48/000000/box.png'%>
  </div>
  <h1><%= @group.name %></h1>
  <div>
    <p></p>
  </div>
  <div>
  </div>
</div>
<main>
  <div>
    <div class="total-banner">
      <h4>Total Amount</h4>
      <p>$<%= @total_amount %></p>
    </div>
    <% if @operations.blank? %>
    <p>No transaction yet.</p>
    <% else %>
    <ul class="card-list">
      <% @operations.each do |payment| %>
        <li class="transaction-card hover">
          <a><h2><%= payment.name %></h2></a>
          <a>$<%= payment.amount %></a>
          <%= button_to "Delete", group_operation_path(group_id: @group.id, id: payment.id), method: :delete, class: "del-btn" %>
        </li>
          <% end %>
        </ul>
      <% end %>

  </div>
  <button class="green-btn" type="button">
    <%= link_to "ADD A NEW TRANSACTION", new_group_operation_path(@group) %>
  </button>
</main>

app/views/home/index.html.erb
<main class="splash-screen">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>  
<div class="app-name">
    <h1>Snapscan</h1>
  </div>  
      <div class="buttons-container">
        <button class="blue-btn">
          <%= link_to 'LOG IN', new_user_session_path %>
        </button>
        <button class="white-btn">
          <%= link_to'SIGN UP', new_user_registration_path %>
        </button>
        </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snapscan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/operations/index.html.erb
<nav>
  <div>
    <%= link_to image_tag("https://img.icons8.com/ios-filled/48/ffffff/long-arrow-left.png"), groups_path, class: "btn"  %>
  </div>
  <h1 class="color-white">TRANSACTIONS</h1>
  <img src="https://img.icons8.com/sf-black/48/ffffff/search.png"/>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="banner">
<div class="cat-image">
    <%= image_tag @group.icon rescue image_tag 'https://img.icons8.com/officel/48/000000/box.png'%>
  </div>
  <h1><%= @group.name %></h1>
  <div>
    <p></p>
  </div>
  <div>
  </div>
</div>
<main>
  <div>
    <% if @operations.blank? %>
    <p>No transaction yet.</p>
    <% else %>
    <ul class="card-list">
      <% @operations.each do |payment| %>
        <li class="transaction-card hover">
          <a><h2><%= payment.name %></h2></a>
          <a>$<%= payment.amount %></a>
          <%= button_to "Delete", group_operation_path(user_id: payment.user.id, group_id: payment.group.id, id: payment.id), method: :delete, class: "del-btn" %>
        </li>
          <% end %>
        </ul>
      <% end %>
      <div class="total-banner">
        <h4>Total Amount</h4>
        <p>$<%=@total_amount %></p>
      </div>
  </div>
  <button class="green-btn" type="button">
    <%= link_to "ADD A NEW TRANSACTION", new_group_operation_path %>
  </button>
</main>

app/views/operations/new.html.erb
<nav>
  <div>
    <%= link_to image_tag("https://img.icons8.com/ios-filled/48/ffffff/long-arrow-left.png"), group_operations_path, class: "btn"  %>
  </div>
  <h1 class="color-white">NEW TRANSACTIONS</h1>
  <img src="https://img.icons8.com/sf-black/48/ffffff/search.png"/>
</nav>
<div class="center">
  <h1>ADD A NEW TRANSACTION</h1>
  <%= form_with model: @operation, url: group_operations_path(@group), data: { turbo: false } do |f| %>
      <br/>
      <br/>
      <%= f.text_field :name, placeholder: 'Name', class: "form-field"%>
      <br/>
      <br/>
      <%= f.number_field :amount, placeholder: 'Amount', class: "form-field"%>
      <br/>
      <br/>
      <%= f.submit 'Add Transaction', class:'green-btn'%>
  <% end %>
</div>

app/views/users/index.html.erb
<main class="splash-screen">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>  
<div class="app-name">
    <h1>Snapscan</h1>
  </div>  
      <div class="buttons-container">
        <button class="blue-btn">
          <%= link_to('LOG IN', "/users/sign_in") %>
        </button>
        <button class="white-btn">
          <%= link_to('SIGN UP', "/users/sign_up") %>
        </button>
        </div>
</main>